17:53:08.154 INFO Test execution started: qqq.test1
17:53:08.155 INFO Browser: chrome
17:53:08.241 ERROR An error ocurred:
Traceback (most recent call last):
  File "C:\iTestin\framework\golem-master\golem\test_runner\test_runner.py", line 122, in run_test
    test_module.test(execution.data)
  File "C:\iTestin\framework\golem-master\projects\test\tests\qqq\test1.py", line 10, in test
    adsf()
NameError: name 'adsf' is not defined
